### ISSUE TITLE
Language filter not working correctly for C++

### ISSUE THREAD

**Issue by mitchellcash** [netlify/staticgen#196] opened 2016-10-09 00:50 UTC
When you attempt to filter by language 'C++' it seems to run into a problem and can't parse it properly.

I am returned 'pub-server' which is JavaScript rather than C++.

**Comment by hartwork** [comment] 2017-06-14 13:02
Could it be that `c++` is interpreted as regular expression and that `+` needs escaping?

**Comment by bdougie** [comment] 2017-07-17 17:38
I am unable to reproduce. I wonder if the new design fixed this. Closing, please reopen if this is reproduced

**Comment by hartwork** [comment] 2017-07-17 18:20
> I am unable to reproduce. I wonder if the new design fixed this. Closing, please reopen if this is reproduced

*Please re-open*, I lack permissions.

To reproduce in either Firefox or Chromium/Chrome:
* go to https://www.staticgen.com/
* reload clearing all caches if you like
* At the "all languages" dropdown selected "C++"
* Watch the listing change to one PHP and one Lua card, no C++ in sight

**Comment by bdougie** [comment] 2017-07-17 18:27
Thanks for the repro steps, definitely still an issue here.

**Comment by hartwork** [comment] 2017-07-17 18:35
Have you tried escaping the pluses, i.e. `C\+\+`?

**Comment by bdougie** [comment] 2017-07-17 21:12
I personally have not and will have to look into this later this week. The project is using [isotope](https://isotope.metafizzy.co/) to filter by language. 

https://github.com/netlify/staticgen/blob/master/source/javascripts/all.js#L33
```js
  $(".projects").isotope({
    layoutMode: "fitRows",
    getSortData: {
      stars: "[data-stars] parseInt",
      forks: "[data-forks] parseInt",
      issues: "[data-issues] parseInt",
      language: "[data-language]",
      title: "[data-title]"
    }
  });
```

**Comment by jayvdb** [comment] 2017-11-20 10:52
I believe `C#` is also broken.

**Closed** 2018-03-14 15:55 UTC
Labels: bug, help wanted
