### ISSUE TITLE
Bug: List tile links to wrong framework

### ISSUE THREAD

**Issue by taviandir** [netlify/staticgen#657] opened 2019-12-01 12:31 UTC
Hello! I appreciate this site as I am new to static generators and am looking for alternatives to use for my own project. However, I encountered a bug on the site.

Expected behaviour: When I click on "brunch" i expect to come to the "brunch" details page.
Actual behaviour: When I click on "brunch" i end up on the "jigsaw" details page.
![image](https://user-images.githubusercontent.com/10051884/69913907-115c2200-143e-11ea-95a6-ae3f5056c8a8.png)

The links redirect correctly for the first options, but somewhere along the list it becomes faulty, to what to me seems to be a "off by one" kind of error. "Jigsaw" (that the "brunch" tile links to) is the option that comes after "Brunch".

**Comment by erquhart** [comment] 2019-12-01 16:46
Can you provide steps to reproduce?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by taviandir** [comment] 2019-12-02 07:58
Ah, yes sorry I forgot that part. :)

Reproduced by changing sorting from default "Stars 7 days" to "Stars total" and some, not all, of the list tiles/items link to something other than what it says.

It seems to work as expected on Chrome, but I can reproduce the error on FF (70.0.1) and Edge (44.18362.449.0).

**Comment by erquhart** [comment] 2019-12-03 18:12
I was able to reproduce in Chrome as well, thanks for the steps. The issue is somewhere between Gatsby Link, Reach Router, and Node <= 10. Spent a while digging in but ultimately fixed by using Node 12. Thanks for opening this!

**Closed by erquhart** 2019-12-03 18:12 UTC

**Comment by taviandir** [comment] 2019-12-04 07:45
No problem, happy to help! :) Glad you solved it!
