### ISSUE TITLE
Supported markup formats field for each Infobox

### ISSUE THREAD

**Issue by fusion809** [netlify/staticgen#166] opened 2016-04-15 13:02 UTC
Hi,

I would like to suggest that each infobox (i.e., the infoboxes shown for each static site generator [SSG] at staticgen's homepage, staticgen.com) also includes a field that shows the supported markup formats for the SSG in question. Similarly to how each infobox also lists supported templating engines. Now I know that many SSGs have some default (or out-of-the-box) supported formats, but they also have optional extensions that add support for additional formats, so I suggest that those that are supported by default and those that require some extra configuration (like the installation of optional extensions) be distinguished from one another, somehow. Perhaps by italicizing those that aren't supported out-of-the-box. 

The reason for this suggestion is pretty simple. I personally, as someone interested in SSGs (and I doubt I'm the only one), am interested in which SSGs support which markup formats. As it makes it easier for me to search for those that are say compatible with posts written in asciidoc and those that only support markdown posts. 

Thanks for your time,
Brenton

**Comment by micheal** [comment] 2016-12-02 04:53
Please and thank you. When it comes to a static site generator, the way I'm going to be writing content is just as important as knowing what language(s) I have to setup to run the tool.

**Comment by biilmann** [comment] 2016-12-02 17:58
Would absolutely take a PR for this. Apart from the UI of sowing the field, the major work to get this done is for someone to actually categorize all the existing static site generators based on what markup formats they support...

**Comment by vassudanagunta** [comment] 2017-10-22 00:50
This is a dupe of #49.

**Comment by erquhart** [comment] 2018-05-14 22:06
Closing in favor of #49.

**Closed by erquhart** 2018-05-14 22:06 UTC
Labels: help wanted
