### ISSUE TITLE
Compatible with Safari 11.1

### ISSUE THREAD

**Issue by DirtyF** [netlify/staticgen#369] opened 2018-05-04 13:35 UTC
Website does not display any text on Safari 11.1 on macOS

![staticgen-safari](https://user-images.githubusercontent.com/103008/39630790-b499e366-4fb0-11e8-949d-c64b3fb8ac52.png)

**Comment by MoOx** [comment] 2018-05-04 13:38
For you information I got the expected result after a few minutes (I just let the window open). Weird as it loads instantly on chrome.

**Comment by erquhart** [comment] 2018-05-07 15:03
hmm loaded instantly in Safari 11.1 just now, maybe a bad build? Can anyone still reproduce?

**Comment by MoOx** [comment] 2018-05-07 15:11
Just got the same problem, again. It seems that https://www.sharebutton.co/fonts/v2/entypo.min.css is ultra slow and completely block the rendering. As soon as I hit the browser cross, display is ok.

**Comment by erquhart** [comment] 2018-05-07 16:24
Ah, looks like that domain is completely down now, I must have gotten a cached version or something.

Getting a fix together for this, thanks for the heads up.

**Comment by erquhart** [comment] 2018-05-14 22:07
Resolved in React Static migration, closing.

**Closed by erquhart** 2018-05-14 22:07 UTC
